### ISSUE TITLE
Redux Funks Usage with Immutable JS

### ISSUE THREAD

**Issue by srikanthkyatham** [mheiber/redux-funk#2]
Would be great if you could provide an example with Immutable js

**Comment by mheiber** [comment]
Thanks for opening this issue.
This library assumes store state is a plain JS object, which unfortunately makes usage with Immutable awkward https://github.com/mheiber/redux-funk/blob/master/src/index.js#L16.

I'd like to keep the LOC and API small (38 LOC), so think the best way of supporting Immutable would be to make another repo for redux-machine-immutable. I could have it ready by Monday. Unless you would be interested in making it, could be fun.

**Comment by srikanthkyatham** [comment]
I could give a shot, btw i have forked this repo and added runFunksImmutable, coalesceFunksImmutable API, well creating another repo might be a good idea.

**Comment by srikanthkyatham** [comment]
I have created 
1. a new repo - https://github.com/srikanthkyatham/redux-funk-immutable
2. package https://www.npmjs.com/package/redux-funk-immutable

**Comment by mheiber** [comment]
Cool! I'll check it out. Thank you
